apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-worker
  template:
    metadata:
      labels:
        app: celery-worker
    spec:
      containers:
        - name: celery
          image: {{ .Values.backend.image }}
          command: {{ toJson .Values.celery.command }}
          env:
            {{- range $key, $val := .Values.backend.env }}
            - name: {{ $key }}
              value: "{{ $val }}"
            {{- end }}