apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-db
  template:
    metadata:
      labels:
        app: flask-db
    spec:
      containers:
        - name: postgres
          image: {{ .Values.postgres.image }}
          ports:
            - containerPort: {{ .Values.postgres.ports.container }}
          env:
            {{- range $key, $val := .Values.postgres.env }}
            - name: {{ $key }}
              value: "{{ $val }}"
            {{- end }}
