apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - port: {{ .Values.backend.ports.container }}
      targetPort: {{ .Values.backend.ports.container }}
      nodePort: {{ .Values.backend.ports.service }}
