apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - port: {{ .Values.frontend.ports.container }}
      targetPort: {{ .Values.frontend.ports.container }}
      nodePort: {{ .Values.frontend.ports.service }}
