apiVersion: v1
kind: Service
metadata:
  name: flask-db
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: flask-db
  ports:
    - port: {{ .Values.postgres.ports.container }}
      targetPort: {{ .Values.postgres.ports.container }}