backend:
  image: harbor.local:8080/dangdangtest/chiatien-backend-v2:latest
  env:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: "1"
    POSTGRES_DB: postgres
    DB_HOST: flask-db
    DB_PORT: 5432
    DB_USER: postgres
    DB_PASSWORD: "1"
    DB_NAME: postgres
    CELERY_BROKER_URL: redis://redis:6379/0
    CELERY_RESULT_BACKEND: redis://redis:6379/1
    MAIL_SERVER: smtp.gmail.com
    MAIL_PORT: 587
    MAIL_USE_TLS: "True"
    MAIL_USERNAME: maitiandewd@gmail.com
    MAIL_PASSWORD: brzo hedf veiy jksi
    MAIL_DEFAULT_SENDER: maitiandewd@gmail.com
  ports:
    container: 5000
    service: 30101

frontend:
  image: harbor.local:8080/dangdangtest/chiatien-frontend-v2:latest
  # env:
  #   REACT_APP_API_BACKEND: http://backend-service:5014/
  ports:
    container: 3000
    service: 30100

postgres:
  image: postgres:16
  ports:
    container: 5432
    service: 5433
  env:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: "1"
    POSTGRES_DB: postgres

redis:
  image: redis:7-alpine
  ports:
    container: 6379
    service: 6380

celery:
  command:
    - celery
    - -A
    - celery_worker.celery
    - worker
    - --loglevel=info
---